name: Python

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install bananomiapy
      run: make
    - name: Tests
      run: pytest
    - name: Test coverage
      if: matrix.python-version == '3.11'
      run: |
        python3 -m "pytest" --cov-report=xml --cov=bananomiapy test/
        codecov